config/routes.rb
Rails.application.routes.draw do

  resources :cats, only: [:create, :destroy, :show ,:update, :index, :new, :edit]

end

app/models/cat.rb
require 'date'
require 'byebug'
class Cat < ActiveRecord::Base
  COLORS = %w(red brown white black)
  validates :color, inclusion: COLORS
  validates :sex, inclusion: %w(M F)
  validates :birth_date, :name, :description, :sex, presence: true

  def age
    (Date.today - birth_date).to_i/365
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
require 'byebug'
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def create
    new_cat = Cat.new(cat_params)
    if new_cat.save
      redirect_to cat_url(new_cat)
    else
      render json: new_cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    @cat.update(cat_params)
    # debugger
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:name,:birth_date,:color,:sex,:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<% action = cat.persisted? ? "patch" : "post" %>
<% request_type = cat.persisted? ? cat_url(cat) : cats_url %>
<form action="<%=request_type%>" method="post">
  <input type="hidden" name="_method" value="<%=action%>">
  <label for="cat_name">Cat Name </label>
  <input type="text" name="cat[name]" id="cat_name" value=<%=cat.name%>>
  <br>
  <label for="cat_birth_day">Cat's Birthday</label>
  <input type="date" name=cat[birth_date] id ="cat_birth_day" value=<%=cat.birth_date%>>
  <br>
  <input type="radio" name="cat[sex]" id="cat_sex_female" value ="F" <%= "checked" if cat.sex == "F" %>>
  <label for="cat_sex_female">Female</label>
  <br>
  <input type="radio" name="cat[sex]" id="cat_sex_male" value ="M"  <%= "checked" if cat.sex == "M" %>>
  <label for="cat_sex_male">Male</label>
  <br>
  <label for="cat_color">Cat color</label>
  <select name="cat[color]" id="cat_color">
    <!-- <option value=" ">Blank</option> -->
    <option <%= "selected" if cat.color == "brown" %> value="brown">Brown</option>
    <!-- <option value="brown">Brown</option> -->
    <option <%= "selected" if cat.color == "black" %> value="black">Black</option>
    <!-- <option value="black">Black</option> -->
    <option <%= "selected" if cat.color == "white" %> value="white">White</option>
    <!-- <option value="white">White</option> -->
    <option <%= "selected" if cat.color == "red" %> value="red">Red</option>
  </select>
  <label for "cat_description">Brief Description of Cat</label>
  <input type="text" name="cat[description]" id="cat_description" value="<%=cat.description%>">
  <br>
  <input type="submit" value="Update cat">
</form>

app/views/cats/_new.html.erb
<form action="cats_url" method="post">
  <label for="cat_name">Cat Name </label>
  <input type="text" name="cat[name]" id="cat_name">
  <br>
  <input type="radio" name="cat[sex]" id="cat_sex_female" value="F">
  <label for="cat_sex_female">Female</label>
  <br>
  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M">
  <label for="cat_sex_male">Male</label>
  <input type="submit" value="Create cat">
  <br>
  <label for="cat_color">Cat color</label>
  <select name="cat[color]" id="cat_color">
    <option value=" ">Blank</option>
    <option value="red">Red</option>
    <option value="brown">Brown</option>
    <option value="black">Black</option>
    <option value="white">White</option>
  </select>
  <input type="submit" value="Create cat">
</form>

app/views/cats/edit.html.erb
<%= render "form", cat: @cat %>

app/views/cats/index.html.erb
<!-- app/views/books/index.html.erb -->
<h1>Listing Cats</h1>

<ul>
  <% @cats.each do |cat| %>
    <li>   <%= "id: #{cat.id}" %>  </li>
    <li>   <%= "name: #{cat.name}" %>  </li>
    <li>   <%= "date of birth: #{cat.birth_date}" %>  </li>
    <li>   <%= "color: #{cat.color}" %>  </li>
    <li>   <%= "age: #{cat.age}" %>  </li>
    <li>   <%= "sex: #{cat.sex}" %>  </li>
    <li>   <%= "description: #{cat.description}" %>  </li>
  <% end %>
</ul>

app/views/cats/new.html.erb
<form action= <%=cats_url%> method="post">
  <label for="cat_name">Cat Name </label>
  <input type="text" name="cat[name]" id="cat_name">
  <br>
  <label for="cat_birth_day">Cat's Birthday</label>
  <input type="date" name=cat[birth_date] id ="cat_birth_day">
  <br>
  <input type="radio" name="cat[sex]" id="cat_sex_female" value="F">
  <label for="cat_sex_female">Female</label>
  <br>
  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M">
  <label for="cat_sex_male">Male</label>
  <br>
  <label for="cat_color">Cat color</label>
  <select name="cat[color]" id="cat_color">
    <option value=" ">Blank</option>
    <option value="red">Red</option>
    <option value="brown">Brown</option>
    <option value="black">Black</option>
    <option value="white">White</option>
  </select>
  <label for "cat_description">Brief Description of Cat</label>
  <input type="text" name="cat[description]" id="cat_description">
  <br>
  <input type="submit" value="Create cat">
</form>

app/views/cats/show.html.erb
<ul>
    <li>   <%= "id: #{@cat[:id]}" %>  </li>
    <li>   <%= "name: #{@cat[:name]}" %>  </li>
    <li>   <%= "date of birth: #{@cat[:birth_date]}" %>  </li>
    <li>   <%= "color: #{@cat[:color]}" %>  </li>
    <li>   <%= "age: #{@cat[:age]}" %>  </li>
    <li>   <%= "sex: #{@cat[:sex]}" %>  </li>
    <li>   <%= "description: #{@cat[:description]}" %>  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>